export const CHANGE_ACTIVE = "CHANGE_ACTIVE";
export const UPDATE_ORACLES = "UPDATE_ORACLES";
export const REQ_CHANGE_ACTIVE = "REQ_CHANGE_ACTIVE";
export const LOAD_PREV_TRANSACTIONS = "LOAD_PREV_TRANSACTIONS";
export const ADD_NEW_TRANSACTION = "ADD_NEW_TRANSACTION";
export const ADD_STABLE_TRANSACTION = "ADD_STABLE_TRANSACTION";
export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";
export const UPDATE_FUND_BALANCE = "UPDATE_FUND_BALANCE";